sudo: required
services:
  - docker

# This section is executed before tests a run
# It's the setup stage
before_install:
  - docker build -t davidraese/docker-react -f Dockerfile.dev .

# Contain commands to run the tests
# if one of the commands returns a statuscode other then 0 Travis-ci assums that the tests failed
script:
  - docker run -e CI=true davidraese/docker-react npm run test

language: generic

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-306516560977"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY

deploy:
  provider: elasticbeanstalk
  region: eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-306516560977"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
